apiVersion: v1
kind: Pod 
metadata: 
  name: secret-pod 
spec: 
  containers:
    - name: httpd-container 
      image: httpd 
      env:
        - name: Username 
          valueFrom:
            secretKeyRef:
              name: my-secret 
              key: username
        - name: Password 
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password