apiVersion: v1
kind: Pod 
metadata:
  name: mount-secret
spec:
  containers:
    - name: mount-container 
      image: httpd
      volumeMounts:
      - name: secret-volume 
        mountPath: /etc/secret
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret