apiVersion: v1
kind: Pod 
metadata:
  name: mountbased-config
spec:
  containers:
    -  name: mount-nginx-container
       image: nginx
       ports:
        - containerPort: 8000
       volumeMounts:
        - name: mount-config 
          mountPath: /etc/congifmap 
  volumes:
  - name: mount-config
    configMap:
      name: my-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configmap-app
  template:
    metadata:
      labels:
        app: configmap-app
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-vol
          mountPath: /etc/config
      volumes:
      - name: config-vol
        configMap:
          name: my-config

